Title: "Devops Discoveries"
languageCode: "en-us"
baseurl: "https://clinta.github.io"
theme: "clinta"
PygmentsCodeFences: true
pygmentsstyle: "friendly"
Author:
  name: "Clint Armstrong"
  email: "clint@clintarmstrong.net"
permalinks:
  post: /:slug/
googleAnalytics: "UA-58778705-1"

Params:
  headerLinks:
    - Posts: /
    - Résumé: /resume
    - Twitter: https://twitter.com/clinta

Indexes:
  tag: "tags"
