title: "Devops Discoveries"
languageCode: "en-us"
baseurl: "https://blag.clintarmstrong.net/"
theme: "heather-hugo"
LanguageCode: ""
Title: ""
PygmentsCodeFences: true
pygmentsstyle: "friendly"
Author:
  name: "Clint Armstrong"
  email: "clint@clintarmstrong.net"
permalinks:
  post: /:title/

Params:
  headerLinks:
    - Posts: /
    - Résumé: /resume
    - Twitter: https://twitter.com/clinta

Indexes:
  tag: "tags"
